Replace brew with manual script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,10 +10,40 @@ os:
 osx_image: xcode7.3
 
 before_install:
-- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
+  # Install OpenSSL
+  # Also set download URLs obtained from https://www.microsoft.com/net/download#core
+  - if test "$TRAVIS_OS_NAME" == "osx"; then
+      brew install openssl;
+      brew link --force openssl;
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=835011";
+    else
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=834989";
+    fi
+
+  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
+
+  # Install .NET CLI
+  - mkdir $DOTNET_INSTALL_DIR
+  - curl -L $DOTNET_SDK_URL -o dotnet_package
+  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
+
+  # Add dotnet to PATH
+  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
+
+  # Update submodules
+  - git submodule update --init --recursive
+
+  # Display dotnet version info
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
 
 install:
-- if test "$TRAVIS_OS_NAME" == "osx"; then brew tap caskroom/cask; brew cask install dotnet; fi
 # - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
 # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
 # - sudo apt-get update
